#!/usr/bin/env bash
# Render a manim scene without having to remember the venv path or the
# TinyTeX PATH export.
#
#   ./render.sh <file.py> [SceneName ...] [manim flags]
#
# Examples:
#   ./render.sh projects/demo/scene.py Demo             # write mp4 at 1080p60
#   ./render.sh projects/demo/scene.py Demo -ql         # write mp4 at 480p15
#   ./render.sh projects/demo/scene.py Demo -p          # ...and open it
#   ./render.sh projects/demo/scene.py Demo -s          # save last frame as png
#   ./render.sh projects/demo/scene.py -a               # every scene in file
#
# Any flag `manim render` accepts is passed straight through. Note that writing
# is the default in Manim Community -- there is no -w, and -p only controls
# whether the result is opened afterwards.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# manim resolves BOTH manim.cfg and every output directory relative to the
# current working directory. Running from anywhere else silently loses the
# config (wrong background, wrong frame rate) and scatters renders into stray
# media/ folders. So: make every path argument absolute, then always run from
# the repo root.
args=()
for a in "$@"; do
  if [[ "$a" != -* && -e "$a" ]]; then
    args+=("$(cd "$(dirname "$a")" && pwd)/$(basename "$a")")
  else
    args+=("$a")
  fi
done
set -- "${args[@]}"
cd "$REPO_ROOT"

# LaTeX lives in TinyTeX, which is not on PATH for non-login shells.
export PATH="$HOME/Library/TinyTeX/bin/universal-darwin:$PATH"

# manim loads scene files via spec_from_file_location, which does not put the
# repo root on sys.path. Without this, `from voiceover import VoiceoverScene`
# fails even though the package sits right next to the scene.
export PYTHONPATH="$REPO_ROOT${PYTHONPATH:+:$PYTHONPATH}"

MANIM="$REPO_ROOT/.venv/bin/manim"
if [[ ! -x "$MANIM" ]]; then
  echo "error: $MANIM not found. Set the venv up with:" >&2
  echo "    uv venv --python 3.12 .venv" >&2
  echo "    uv pip install --python .venv/bin/python -e ../manim-ce" >&2
  exit 1
fi

# Group a chapter's renders under media/videos/<project>/<chapter>/ instead of
# letting manim flatten every scene file in the repo into media/videos/<stem>/.
#
# The rule itself lives in tools/output_path.py, because build.sh's freshness
# guard asks that file where a render will land and compares mtimes around the
# attempt. If this script and that one ever disagreed about the path, the guard
# would stat a file the render never wrote and report every scene as fresh. So
# ask for the template rather than restating it here.
#
# It has to arrive as a config FILE: manim exposes --media_dir on the command
# line but not video_dir, which is settable only through a .cfg. And -c makes
# manim IGNORE the folder-wide manim.cfg (manim/_config/utils.py,
# make_config_parser) rather than layering on top of it -- so the generated
# file is manim.cfg itself plus one appended line, regenerated every run. Every
# key in manim.cfg sits under its single [CLI] section, so appending lands in
# the right section, and manim.cfg's relative paths still resolve because we
# have already cd'd to the repo root.
SRC=""
for a in "$@"; do
  if [[ "$a" != -* && -f "$a" && "$a" == *.py ]]; then SRC="$a"; break; fi
done

if [[ -n "$SRC" ]]; then
  VIDEO_DIR_TEMPLATE="$("$REPO_ROOT/.venv/bin/python" \
    "$REPO_ROOT/tools/output_path.py" --video-dir-template "$SRC")"
  if [[ -n "$VIDEO_DIR_TEMPLATE" ]]; then
    # Named after the chapter, so two chapters can render at once. Two renders
    # of the SAME chapter write identical bytes, so that race is harmless.
    slug="$(printf '%s' "$VIDEO_DIR_TEMPLATE" | sed 's|{media_dir}/videos/||; s|/{module_name}/{quality}||; s|/|-|g')"
    GENERATED_CFG="$REPO_ROOT/media/.manim-cfg/$slug.cfg"
    mkdir -p "$(dirname "$GENERATED_CFG")"
    {
      cat "$REPO_ROOT/manim.cfg"
      printf '\n# --- generated by render.sh, do not edit ---------------------\n'
      printf '# Regenerated from manim.cfg on every run; see render.sh.\n'
      printf 'video_dir = %s\n' "$VIDEO_DIR_TEMPLATE"
    } > "$GENERATED_CFG"
    set -- "$@" --config_file "$GENERATED_CFG"
  fi
fi

exec "$MANIM" render "$@"
